Digital Penguins: Object.h File Reference
Object.h File Reference
Game Object.
Typedefs
typedef void(* ObjInit)()
Object init function type.
typedef void(* ObjUpdate)()
Object update function type.
typedef struct Object Object
Game Object.
Functions
Object * Object_new (ObjInit init, ObjUpdate update)
Create new Object.
void Object_delete (Object *obj)
Delete Object.
void Object_init (Object *obj)
Initialize Object.
void Object_update (Object *obj)
Update Object.
Detailed Description
Game Object.
Author
Arthur Bouvier
Definition in file Object.h.
Typedef Documentation
typedef struct Object Object
Game Object.
Definition at line 14 of file Object.h.
typedef void(* ObjInit)()
Object init function type.
Definition at line 8 of file Object.h.
typedef void(* ObjUpdate)()
Object update function type.
Definition at line 9 of file Object.h.
Function Documentation
void Object_delete (Object * obj)
Delete Object.
Parameters
obj Object to delete
Definition at line 25 of file Object.c.
{
     free(obj);
 }
void Object_init (Object * obj)
Initialize Object.
Parameters
obj Object to initialize
Definition at line 29 of file Object.c.
References Object::init.
Referenced by ObjectManager_addObj().
{
     if (obj->init)
         obj->init();
 }
Object* Object_new (ObjInit init, ObjUpdate update)
Create new Object.
Parameters
init Init function for new Object
update Update function for new Object
Returns
New Object
Definition at line 16 of file Object.c.
References Object::init, and Object::update.
Referenced by ExampleObj_new().
{
     Object *obj = malloc(sizeof(Object));
     obj->init = init;
     obj->update = update;
     return obj;
 }
void Object_update (Object * obj)
Update Object.
Parameters
obj Object to Update
Definition at line 34 of file Object.c.
References Object::update.
Referenced by ObjectManager_update().
{
     if (obj->update)
         obj->update();
 }