Digital Penguins: LevelManager.c File Reference
LevelManager.c File Reference
Handle loading and switching levels.
#include "stdafx.h"
#include "LevelManager.h"
Classes
struct Level
Functions
void LevelManager_init ()
Initialize the level manager.
static int LevelIsChanging ()
void LevelManager_update (float dt)
Update the level manager.
void LevelManager_shutdown ()
Shutdown the level manager.
int LevelManager_isRestarting ()
Determine if the current level is being restarted.
int LevelManager_isRunning ()
Determine if the game is still running.
void LevelManager_setNextLevel (Levels nextLevel)
Set the next level to run.
Variables
static Level level
Detailed Description
Handle loading and switching levels.
Author
Brand Knutson
Date
1/10/2019
Definition in file LevelManager.c.
Function Documentation
static int LevelIsChanging () static
Definition at line 71 of file LevelManager.c.
References Level::current, and Level::next.
Referenced by LevelManager_update().
{
     return level.current != level.next;
 }
void LevelManager_init ()
Initialize the level manager.
Definition at line 19 of file LevelManager.c.
References Level::current, InitialLevel, LevelInvalid, Level::next, and Level::previous.
 {
     level.current = LevelInvalid;
     level.previous = LevelInvalid;
     level.next = InitialLevel;
 }
int LevelManager_isRestarting ()
Determine if the current level is being restarted.
Returns
Whether or not the current level is restarting.
Definition at line 54 of file LevelManager.c.
References LevelRestart, and Level::next.
Referenced by LevelManager_update().
 {
     return level.next == LevelRestart;
 }
int LevelManager_isRunning ()
Determine if the game is still running.
Returns
Whether or not the LevelManager is currently running.
Definition at line 59 of file LevelManager.c.
References Level::current, and LevelQuit.
 {
     return level.current != LevelQuit;
 }
void LevelManager_setNextLevel (Levels nextLevel)
Set the next level to run.
Parameters
nextLevel The next level to load.
Definition at line 64 of file LevelManager.c.
References Level_isSpecial(), Level_isValid(), and Level::next.
 {
     if (Level_isValid(nextLevel) || Level_isSpecial(nextLevel)) {
         level.next = nextLevel;
     }
 }
void LevelManager_shutdown ()
Shutdown the level manager.
Definition at line 50 of file LevelManager.c.
 {
 }
void LevelManager_update (float dt)
Update the level manager.
Parameters
dt Delta Time for updates.
Definition at line 28 of file LevelManager.c.
References Level::current, Level_init(), Level_load(), Level_shutdown(), Level_unload(), Level_update(), LevelIsChanging(), LevelManager_isRestarting(), Level::next, and Level::previous.
 {
     if (LevelIsChanging()) {
         Level_shutdown(level.current);
         if (!LevelManager_isRestarting()) Level_unload(level.current);
         level.previous = level.current;
         level.current = level.next;
         if (!LevelManager_isRestarting()) Level_load(level.current);
         else {
             level.current = level.previous;
             level.next = level.current;
         }
         Level_init(level.current);
     }
     Level_update(level.current, dt);
 }
Variable Documentation
Level level static
Definition at line 17 of file LevelManager.c.
Referenced by Level_init(), Level_load(), Level_shutdown(), Level_unload(), and Level_update().