Digital Penguins: LevelTable.h File Reference
LevelTable.h File Reference
List of all levels.
Enumerations
enum Levels {
LevelQuit = -3, LevelRestart = -2, LevelInvalid = -1, Level1,
LevelNum, LastLevel = LevelNum - 1, InitialLevel = Level1
}
Enum for easily accessing each level from the table.
Functions
int Level_isValid (Levels level)
Check if level is valid.
int Level_isSpecial (Levels level)
Check if the level is.
void Level_load (Levels level)
Load a level.
void Level_init (Levels level)
Initialize a level.
void Level_update (Levels level, float dt)
Update a level.
void Level_shutdown (Levels level)
Shutdown a level.
void Level_unload (Levels level)
Unload a level.
Detailed Description
List of all levels.
Author
Brand Knutson
Date
1/10/2019
Definition in file LevelTable.h.
Enumeration Type Documentation
enum Levels
Enum for easily accessing each level from the table.
Enumerator
LevelQuit
LevelRestart
LevelInvalid
Level1
LevelNum
LastLevel
InitialLevel
Definition at line 14 of file LevelTable.h.
 {
     LevelQuit = -3,
     LevelRestart = -2,
     LevelInvalid = -1,
     //Game levels.
     Level1,
     //Extra info
     LevelNum,
     LastLevel = LevelNum - 1,
     //Initial level.
     InitialLevel = Level1
 } Levels;
Function Documentation
void Level_init (Levels level)
Initialize a level.
Parameters
level Level to initialize.
Definition at line 46 of file LevelTable.c.
References level, Level_isValid(), and TableEntry::levelInit.
Referenced by LevelManager_update().
 {
     if (Level_isValid(level) && (*LevelTable[level].levelInit) != NULL) (*LevelTable[level].levelInit)();
 }
int Level_isSpecial (Levels level)
Check if the level is.
Parameters
level The level to check if is special (I.E. quitting or restarting).
Returns
Whether or not the level is special.
Definition at line 36 of file LevelTable.c.
References LevelQuit, and LevelRestart.
Referenced by LevelManager_setNextLevel().
 {
     return level == LevelQuit || level == LevelRestart;
 }
int Level_isValid (Levels level)
Check if level is valid.
Parameters
level The level to check if actually exists.
Returns
Whether or not the level is valid.
Definition at line 31 of file LevelTable.c.
References LevelNum.
Referenced by Level_init(), Level_load(), Level_shutdown(), Level_unload(), Level_update(), and LevelManager_setNextLevel().
 {
     return ((level >= 0) && (level < LevelNum));
 }
void Level_load (Levels level)
Load a level.
Parameters
level Level to load.
Definition at line 41 of file LevelTable.c.
References level, Level_isValid(), and TableEntry::levelLoad.
Referenced by LevelManager_update().
 {
     if (Level_isValid(level) && (*LevelTable[level].levelLoad) != NULL) (*LevelTable[level].levelLoad)();
 }
void Level_shutdown (Levels level)
Shutdown a level.
Parameters
level to shutdown.
Definition at line 56 of file LevelTable.c.
References level, Level_isValid(), and TableEntry::levelShutdown.
Referenced by LevelManager_update().
 {
     if (Level_isValid(level) && ((*LevelTable[level].levelShutdown) != NULL)) (*LevelTable[level].levelShutdown)();
 }
void Level_unload (Levels level)
Unload a level.
Parameters
level to unload.
Definition at line 61 of file LevelTable.c.
References level, Level_isValid(), and TableEntry::levelUnload.
Referenced by LevelManager_update().
 {
     if (Level_isValid(level) && ((*LevelTable[level].levelUnload) != NULL)) (*LevelTable[level].levelUnload)();
 }
void Level_update (Levels level, float dt)
Update a level.
Parameters
level Level to update.
dt DeltaTime for updates.
Definition at line 51 of file LevelTable.c.
References level, Level_isValid(), and TableEntry::levelUpdate.
Referenced by LevelManager_update().
 {
     if (Level_isValid(level) && ((*LevelTable[level].levelUpdate) != NULL)) (*LevelTable[level].levelUpdate)(dt);
 }