Digital Penguins: Vector.c File Reference
Vector.c File Reference
vector implementation
#include "stdafx.h"
#include "Vector.h"
Classes
struct vector
Functions
vector * vector_new (size_t max)
Create new vector.
void vector_delete (vector *vec)
Delete vector.
size_t vector_size (vector *vec)
Get size of vector.
size_t vector_max_size (vector *vec)
Get max size of vector.
int vector_empty (vector *vec)
Check if vector is empty.
void vector_reserve (vector *vec, size_t max)
Reserve space for the vector array.
void * vector_at (vector *vec, unsigned i)
Get item in vector.
void vector_push_back (vector *vec, void *item)
Add item to the back of a vector.
Detailed Description
vector implementation
Author
Arthur Bouvier
Definition in file Vector.c.
Function Documentation
void* vector_at (vector * vec, unsigned i)
Get item in vector.
Parameters
vec vector to get from
i Index at which to get item
Returns
Item in vector at given index
Definition at line 51 of file Vector.c.
References vector::data.
Referenced by ObjectManager_update().
{
     return vec->data[i];
 }
void vector_delete (vector * vec)
Delete vector.
Parameters
vec vector to delete
Definition at line 24 of file Vector.c.
References vector::data.
Referenced by ObjectManager_end().
{
     free(vec->data);
     free(vec);
 }
int vector_empty (vector * vec)
Check if vector is empty.
Parameters
vec vector to check
Returns
Whether it is empty
Definition at line 37 of file Vector.c.
References vector::size.
{
     return vec->size == 0;
 }
size_t vector_max_size (vector * vec)
Get max size of vector.
Parameters
vec vector to get max size of
Returns
Max size of vector
Definition at line 33 of file Vector.c.
References vector::max.
{
     return vec->max;
 }
vector* vector_new (size_t max)
Create new vector.
Parameters
max Starting array allocation size
Returns
New vector
Definition at line 16 of file Vector.c.
References vector::data, vector::max, and vector::size.
Referenced by ObjectManager_init().
{
     vector *vec = malloc(sizeof(vector));
     vec->max = max;
     vec->size = 0;
     vec->data = malloc(sizeof(void*) * max);
     return vec;
 }
void vector_push_back (vector * vec, void * item)
Add item to the back of a vector.
Parameters
vec vector to add to
item Item to add
Definition at line 55 of file Vector.c.
References vector::data, vector::max, vector::size, and vector_reserve().
Referenced by ObjectManager_addObj().
{
     if (vec->size + 1 >= vec->max)
         vector_reserve(vec, vec->max * 2);
     vec->data[vec->size++] = item;
 }
void vector_reserve (vector * vec, size_t max)
Reserve space for the vector array.
Parameters
vec vector to reserve for
max New max size of vector
Definition at line 41 of file Vector.c.
References vector::data, vector::max, and vector::size.
Referenced by vector_push_back().
{
     if (max > vec->max) {
         vec->max = max;
         void *data = vec->data;
         vec->data = malloc(sizeof(void*) * max);
         memcpy(vec->data, data, sizeof(void*) * vec->size);
         free(data);
     }
 }
size_t vector_size (vector * vec)
Get size of vector.
Parameters
vec vector to get size of
Returns
Size of vector
Definition at line 29 of file Vector.c.
References vector::size.
Referenced by ObjectManager_update().
{
     return vec->size;
 }